name: docker
on:
  push:
    tags:
       - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-20.04, debian-10]
        include:
          - os: ubuntu-20.04
            family: ubuntu
            version: 20.04
          - os: debian-10
            family: debian
            version: 10
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u fastide --password-stdin
      - name: build
        run: |
          docker buildx build \
            -t fastide/${{ matrix.family }}:${{ matrix.version }} \
            --platform=linux/amd64,darwin/amd64 \
            --build-arg OS_FAMILY=${{ matrix.family }} \
            --build-arg OS_VERSION=${{ matrix.version }} \
            --push .
