name: docker
on:
  push:
    tags:
       - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, centos-8, fedora-31]
        include:
          - os: ubuntu-18.04
            family: ubuntu
            version: 18.04
          - os: ubuntu-20.04
            family: ubuntu
            version: 20.04
          - os: centos-8
            family: centos
            version: 8
          - os: fedora-31
            family: fedora
            version: 31
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u fastide --password-stdin
      - name: build
        run: |
          docker buildx build \
            -t fastide/${{ matrix.family }}:${{ matrix.version }} \
            --platform=linux/amd64,linux/386,linux/arm64,darwin/amd64 \
            --build-arg OS_FAMILY=${{ matrix.family }} \
            --build-arg OS_VERSION=${{ matrix.version }} \
            --push .
