name: ci_unix
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          cd toolbox && make all &&
          cd .. && make install
